---
project: fwk_core
title: XCORE Core Framework
version: 1.0.2

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  linkcheck_ignore_regex: [".*github.com/xmos.*"]
  doxygen_projects:
    fwk_core:
      doxyfile_path: doc/Doxyfile.inc
